language: node_js
node_js:
  - "0.10"
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-projectfiles' ]; then cd .. && eval "mv $currentfolder generator-projectfiles" && cd generator-projectfiles; fi

